name: env1_adultcensus
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=gpu_0
  - asttokens=3.0.0=py39haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_ha590de0_openblas
  - bottleneck=1.4.2=py39hc99e966_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2026.1.4=h4c7d964_0
  - colorama=0.4.6=py39haa95532_0
  - comm=0.2.1=py39haa95532_0
  - cuda-version=12.9=h4f385c5_3
  - debugpy=1.8.16=py39h885b0b7_0
  - decorator=5.2.1=py39haa95532_0
  - et_xmlfile=2.0.0=py39haa95532_0
  - executing=2.2.1=py39haa95532_0
  - expat=2.7.3=h885b0b7_4
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - importlib_metadata=8.7.0=hd3eb1b0_0
  - ipykernel=6.30.1=py39haa95532_0
  - ipython=8.15.0=py39haa95532_0
  - jedi=0.19.2=py39haa95532_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=py39haa95532_0
  - jupyter_core=5.8.1=py39haa95532_0
  - libblas=3.11.0=5_h0adab6e_openblas
  - libcblas=3.11.0=5_h2a8eebe_openblas
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hd232482_openblas
  - liblapacke=3.11.0=5_hbb0e6ff_openblas
  - libopenblas=0.3.30=hf885159_2
  - libsodium=1.0.20=h83e8143_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxgboost=2.1.4=cuda128_hace5437_2
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - matplotlib-inline=0.1.7=py39haa95532_0
  - mkl=2025.3.0=hac47afa_454
  - nest-asyncio=1.6.0=py39haa95532_0
  - nomkl=3.0=0
  - numexpr=2.10.2=py39h545706d_100
  - numpy=2.0.2=py39h60232e0_1
  - openblas=0.3.30=hfe2e4d6_2
  - openblas-devel=0.3.30=hfe9b8b4_2
  - openpyxl=3.1.5=py39h827c3e9_1
  - openssl=3.6.1=hf411b9b_1
  - packaging=25.0=py39haa95532_1
  - pandas=2.3.3=py39ha5e6156_0
  - parso=0.8.4=py39haa95532_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.3=pyhc872135_0
  - platformdirs=4.3.7=py39haa95532_0
  - prompt-toolkit=3.0.52=py39haa95532_1
  - psutil=7.0.0=py39h02ab6af_1
  - pure_eval=0.2.3=py39haa95532_0
  - py-xgboost=2.1.4=cuda128_pyh71c493a_2
  - pygments=2.19.1=py39haa95532_0
  - python=3.9.25=h716150d_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pywin32=311=py39h885b0b7_0
  - pyzmq=27.1.0=py39h7149c55_0
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.13.1=py39h1a10956_0
  - setuptools=80.9.0=py39haa95532_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=py39haa95532_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py39h827c3e9_0
  - traitlets=5.14.3=py39haa95532_0
  - typing-extensions=4.15.0=py39haa95532_0
  - typing_extensions=4.15.0=py39haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py39haa95532_0
  - wheel=0.45.1=py39haa95532_0
  - xgboost=2.1.4=cuda128_pyh68bd8d9_2
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alembic==1.16.5
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - databricks-sdk==0.76.0
      - datasets==4.5.0
      - dill==0.4.0
      - docker==7.1.0
      - exceptiongroup==1.3.1
      - fastapi==0.128.0
      - filelock==3.19.1
      - flask==3.1.2
      - flatbuffers==25.12.19
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - gast==0.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.45.0
      - google-pasta==0.2.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.2.4
      - grpcio==1.78.0
      - h11==0.16.0
      - h5py==3.14.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - idna==3.11
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - keras==3.10.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mlflow==3.1.4
      - mlflow-skinny==3.1.4
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - namex==0.1.0
      - networkx==3.2.1
      - opentelemetry-api==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opt-einsum==3.4.0
      - optree==0.18.0
      - optuna==4.7.0
      - patsy==1.0.2
      - pillow==11.3.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyparsing==3.3.1
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.3.2
      - rsa==4.9.1
      - safetensors==0.7.0
      - seaborn==0.13.2
      - shellingham==1.5.4
      - smmap==5.0.2
      - sqlalchemy==2.0.45
      - sqlparse==0.5.5
      - starlette==0.49.3
      - statsmodels==0.14.6
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - tokenizers==0.22.2
      - tomli==2.3.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.3
      - transformers==4.57.6
      - typer==0.23.2
      - typer-slim==0.23.2
      - typing-inspection==0.4.2
      - urllib3==2.6.2
      - uvicorn==0.39.0
      - waitress==3.0.2
      - werkzeug==3.1.4
      - wrapt==2.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\daois\anaconda3\envs\env1_adultcensus
